name: fbfeeds
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - atomicwrites=1.3.0=py_0
  - attrs=19.3.0=py_0
  - ca-certificates=2021.10.8=h5b45459_0
  - certifi=2021.10.8=py38haa244fe_1
  - colorama=0.4.3=py_0
  - entrypoints=0.3=py38h32f6830_1001
  - importlib_metadata=1.5.0=py38_0
  - libiconv=1.15=hfa6e2cd_1005
  - libxml2=2.9.10=h9ce36c8_0
  - libxslt=1.1.33=heafd4d3_0
  - mccabe=0.6.1=py_1
  - more-itertools=8.2.0=py_0
  - openssl=1.1.1l=h8ffe710_0
  - packaging=20.1=py_0
  - pip=21.3.1=pyhd8ed1ab_0
  - pyparsing=2.4.6=py_0
  - python=3.8.5=h5fd99cc_2_cpython
  - python_abi=3.8=1_cp38
  - sqlite=3.32.3=he774522_1
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_1
  - wcwidth=0.1.8=py_0
  - wheel=0.34.2=py_1
  - wincertstore=0.2=py38_1003
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h2fa13f4_1006
  - pip:
    - beautifulsoup4==4.10.0
    - bleach==4.1.0
    - chardet==3.0.4
    - charset-normalizer==2.0.8
    - click==6.7
    - flake8==4.0.1
    - flask==1.1.4
    - idna==2.7
    - iniconfig==1.0.1
    - itsdangerous==0.24
    - jinja2==2.11.3
    - lxml==4.6.4
    - markupsafe==2.0.1
    - pluggy==0.13.1
    - py==1.11.0
    - pycodestyle==2.8.0
    - pyflakes==2.4.0
    - pytest==6.2.5
    - python-dateutil==2.8.2
    - requests==2.26.0
    - setuptools==59.4.0
    - six==1.15.0
    - soupsieve==1.9.1
    - toml==0.10.1
    - urllib3==1.26.7
    - webencodings==0.5.1
    - werkzeug==0.15.5
prefix: C:\Users\ic\Miniconda3\envs\fbfeeds
